#!/bin/bash

# Folder lokacija gde se slike nalaze
WEB_LOKACIJA="$1"

# Boja pozadine slika
BOJA_POZADINE='#FFFFFF' # transparent - za providno

if [[ -z "$WEB_LOKACIJA" ]]; then
    echo 'ERROR - Lokacija nije navedena. Potrebno je: ./adapterslika /putanja/do/foldera'
    exit 1
fi

while IFS= read -r -d '' SLIKE; do

    # Skip za .comments
    if [[ "$SLIKE" == */.comments/* ]]; then
        echo "Preskačem komentar fajl: $SLIKE"
        continue
    fi

    # Uzmi dimenzije
    sirina=$(identify -format "%w" "$SLIKE" 2>/dev/null)
    visina=$(identify -format "%h" "$SLIKE" 2>/dev/null)

    # Validacija za brojeve
    if ! [[ "$sirina" =~ ^[0-9]+$ && "$visina" =~ ^[0-9]+$ ]]; then
        echo "Preskačem - Ne mogu da pročitam sliku: '$SLIKE'"
        continue
    fi

    # Poređenje i adaptacija
    if [[ $sirina -le 250 && $visina -le 250 ]]; then
        echo "Preskačem - Slika suviše mala: '$SLIKE'"
    elif [[ $sirina -eq 1100 && $visina -eq 800 ]]; then
        echo "Preskačem - Slika je već tražene veličine: '$SLIKE'"
    else
        echo "Menjam veličinu za sliku: '$SLIKE'"
        mogrify -strip -resize 820x820 -extent 1100x800 -gravity center -background "$BOJA_POZADINE" "$SLIKE"
    fi

done < <(find "$WEB_LOKACIJA" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" -o -iname "*.png" -o -iname "*.webp" \) -print0)
